USER_CONSTANTS = {
    'MIN_LENGTH_EMAIL': 5,
    'MAX_LENGTH_EMAIL': 254,
    'MAX_LENGTH_FIRST_NAME': 254,
    'MIN_LENGTH_FIRST_NAME': 3,
    'MAX_LENGTH_LAST_NAME': 254,
    'MIN_LENGTH_LAST_NAME': 3,
    'MAX_LENGTH_PATRONYMIC': 254,
    'MIN_LENGTH_PATRONYMIC': 3,
    'MIN_LENGTH_PASSWORD': 8,
    'MAX_LENGTH_PASSWORD': 1024
}
