# Generated by Django 5.2 on 2025-04-18 16:08

import django.db.models.deletion
import utils_app.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Повод сбора',
                'verbose_name_plural': 'Поводы сбора',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название')),
                ('description', models.CharField(max_length=512, verbose_name='Описание')),
                ('collect_target', models.PositiveBigIntegerField(verbose_name='Планируемая сумма сбора')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=utils_app.utils.image_file_path, verbose_name='Обложка сбора')),
                ('collection_end_date', models.DateTimeField(verbose_name='Дата окончания сбора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('collect_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_app.collecttype', verbose_name='Тип повода сбора')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Сумма пожертвования')),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collect_app.collect', verbose_name='Сбор')),
                ('donater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Жертвователь')),
            ],
        ),
    ]
