# Generated by Django 5.2 on 2025-04-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collect',
            options={'default_related_name': 'collects', 'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='collecttype',
            options={'default_related_name': 'collect_types', 'verbose_name': 'Повод сбора', 'verbose_name_plural': 'Поводы сбора'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'default_related_name': 'payments', 'verbose_name': 'Пожертвование', 'verbose_name_plural': 'Пожертвования'},
        ),
    ]
