# Generated by Django 5.2 on 2025-04-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0002_alter_collect_options_alter_collecttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания пожертвования'),
            preserve_default=False,
        ),
    ]
