# Generated by Django 5.2 on 2025-04-19 09:23

import collect_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0003_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='collect_target',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Планируемая сумма сбора'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='collection_end_date',
            field=models.DateTimeField(validators=[collect_app.validators.check_date_end_collect], verbose_name='Дата окончания сбора'),
        ),
    ]
