# Generated by Django 5.2 on 2025-04-29 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_app', '0005_alter_collect_collect_target_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания сбора'),
            preserve_default=False,
        ),
    ]
